name       : libvorbis
version    : 1.3.6
release    : 10
source     :
    - https://ftp.osuosl.org/pub/xiph/releases/vorbis/libvorbis-1.3.6.tar.xz : af00bb5a784e7c9e69f56823de4637c350643deedaf333d0fa86ecdba6fcb415
license    : BSD-3-Clause
component  : multimedia.codecs
optimize   : speed
emul32     : yes
summary    : Open source audio format
description: |
    The libvorbis package contains a general purpose audio and music encoding format. This is useful for creating (encoding) and playing (decoding) sound in an open (patent free) format.
builddeps  :
    - pkgconfig32(ogg)
patterns   :
    - docs : /usr/share/doc
setup      : |
    %patch -p1 < $pkgfiles/security/CVE-2017-14160.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
profile    : |
    %make LIBS=-lm check -j1
check      : |
    %make check -j1
