name       : libvorbis
version    : 1.3.5
release    : 8
source     :
    - http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.5.tar.xz : 54f94a9527ff0a88477be0a71c0bab09a4c3febe0ed878b24824906cd4b0e1d1
license    :
    - BSD-3-Clause
summary    : Open source audio format
component  : multimedia.codecs
optimize   : speed
emul32     : yes
builddeps  :
    - pkgconfig(ogg)
    - pkgconfig32(ogg)
patterns   :
    - docs : /usr/share/doc
description: |
    The libvorbis package contains a general purpose audio and music encoding format. This is useful for creating (encoding) and playing (decoding) sound in an open (patent free) format.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
profile    : |
    %make LIBS=-lm check -j1
check      : |
    %make LIBS=-lm check -j1
